export const plans = [
  {
    name: "Starter",
    accent: "#ef4444",
    price: "$499",
    per: "/per project",
    desc: "Perfect for small businesses needing a clean, professional web presence.",
    features: [
      "Landing page design & development",
      "Responsive & mobile-friendly",
      "Basic SEO optimization",
      "1 round of revisions",
      "Delivery in 5–7 days",
    ],
    highlight: false,
  },
  {
    name: "Professional",
    accent: "#22c55e",
    price: "$1,499",
    per: "/per project",
    desc: "Ideal for growing businesses that need a custom multi-page website or web app.",
    features: [
      "Up to 5 pages design & dev",
      "Custom UI/UX design in Figma",
      "React / Next.js development",
      "CMS or admin panel integration",
      "3 rounds of revisions",
      "Delivery in 2–3 weeks",
    ],
    highlight: true,
  },
  {
    name: "Enterprise",
    accent: "#ef4444",
    price: "Custom",
    per: "/let's talk",
    desc: "Full-scale SaaS or web application with end-to-end design and development.",
    features: [
      "Full SaaS / web app development",
      "Complete design system",
      "Backend API & database",
      "Authentication & payments",
      "Ongoing support & iterations",
      "Dedicated communication channel",
    ],
    highlight: false,
  },
];
